### ISSUE TITLE
[iOS bootcamp] Project 2

### ISSUE THREAD

**Issue by henryou007** [henryou007/YelpApp#1]
Yelp Homework Submission @codepath

**Comment by timothy1ee** [comment]
Tagging w/ @codepathreview so it's picked up by the submission tracker.

**Comment by codepathreview** [comment]
Hi Henry,

:+1: nice work. The primary challenge of this homework was to learn how to use UITableView to manage a complex form, establish communication between view controllers, and apply the correct Auto Layout constraints. A few notes after checking out the code:
- For the restaurant cell, note that you should move all unnecessarily public properties to the private class extension in the .m file.
- Note that you should resolve all the Auto Layout constraint warnings in your nibs.
- Nice work linking the filter model with the controls. See this [popular form library](https://github.com/nicklockwood/FXForms) for an alternative to implementing forms manually.
- Nice work connecting the view controllers via the custom filter delegate. This is a popular pattern for handling events between view controllers.

This was a challenging assignment, congrats on completing it successfully!
